### ISSUE TITLE
[please fix] ice and fire silver ore can't be processed

### ISSUE THREAD

**Issue by kreezxil** [kreezxil/World-of-Dragons#197]
this is a note myself

**Comment by kreezxil** [comment]
done

**Comment by Bloutware** [comment]
how did you fix it?

**Comment by kreezxil** [comment]
I used crafttweaker make a recipe that either converts it, removes it, or adds it to a furnace, feel free to analyze my scripts.

**Comment by Bloutware** [comment]
Thanks, It worked

Only in furnace tho (I thought I could put it in Tinker's smeltery too)

**Comment by d0ob** [comment]
Hi there. I still have this problem, ore can't be smelt.. In JEI when I look the recipe for ingot it show me the smelt part but with a blank space where the ore should be; and no recipe pop up when looking for the ore.
